// This file is generated by ./updateCacheFile.ts
import { Country } from "./types.ts";

export type CountryCode =
  | "AD"
  | "AE"
  | "AF"
  | "AG"
  | "AI"
  | "AL"
  | "AM"
  | "AN"
  | "AO"
  | "AQ"
  | "AR"
  | "AS"
  | "AT"
  | "AU"
  | "AW"
  | "AZ"
  | "BA"
  | "BB"
  | "BD"
  | "BE"
  | "BF"
  | "BG"
  | "BH"
  | "BI"
  | "BJ"
  | "BM"
  | "BN"
  | "BO"
  | "BR"
  | "BS"
  | "BT"
  | "BU"
  | "BV"
  | "BW"
  | "BY"
  | "BZ"
  | "CA"
  | "CC"
  | "CD"
  | "CF"
  | "CG"
  | "CH"
  | "CI"
  | "CK"
  | "CL"
  | "CM"
  | "CN"
  | "CO"
  | "CR"
  | "CS"
  | "CU"
  | "CV"
  | "CX"
  | "CY"
  | "CZ"
  | "DE"
  | "DJ"
  | "DK"
  | "DM"
  | "DO"
  | "DZ"
  | "EC"
  | "EE"
  | "EG"
  | "EH"
  | "ER"
  | "ES"
  | "ET"
  | "FI"
  | "FJ"
  | "FK"
  | "FM"
  | "FO"
  | "FR"
  | "GA"
  | "GB"
  | "GD"
  | "GE"
  | "GF"
  | "GH"
  | "GI"
  | "GL"
  | "GM"
  | "GN"
  | "GP"
  | "GQ"
  | "GR"
  | "GS"
  | "GT"
  | "GU"
  | "GW"
  | "GY"
  | "HK"
  | "HM"
  | "HN"
  | "HR"
  | "HT"
  | "HU"
  | "ID"
  | "IE"
  | "IL"
  | "IN"
  | "IO"
  | "IQ"
  | "IR"
  | "IS"
  | "IT"
  | "JM"
  | "JO"
  | "JP"
  | "KE"
  | "KG"
  | "KH"
  | "KI"
  | "KM"
  | "KN"
  | "KP"
  | "KR"
  | "KW"
  | "KY"
  | "KZ"
  | "LA"
  | "LB"
  | "LC"
  | "LI"
  | "LK"
  | "LR"
  | "LS"
  | "LT"
  | "LU"
  | "LV"
  | "LY"
  | "MA"
  | "MC"
  | "MD"
  | "ME"
  | "MG"
  | "MH"
  | "MK"
  | "ML"
  | "MM"
  | "MN"
  | "MO"
  | "MP"
  | "MQ"
  | "MR"
  | "MS"
  | "MT"
  | "MU"
  | "MV"
  | "MW"
  | "MX"
  | "MY"
  | "MZ"
  | "NA"
  | "NC"
  | "NE"
  | "NF"
  | "NG"
  | "NI"
  | "NL"
  | "NO"
  | "NP"
  | "NR"
  | "NU"
  | "NZ"
  | "OM"
  | "PA"
  | "PE"
  | "PF"
  | "PG"
  | "PH"
  | "PK"
  | "PL"
  | "PM"
  | "PN"
  | "PR"
  | "PS"
  | "PT"
  | "PW"
  | "PY"
  | "QA"
  | "RE"
  | "RO"
  | "RS"
  | "RU"
  | "RW"
  | "SA"
  | "SB"
  | "SC"
  | "SD"
  | "SE"
  | "SG"
  | "SH"
  | "SI"
  | "SJ"
  | "SK"
  | "SL"
  | "SM"
  | "SN"
  | "SO"
  | "SR"
  | "SS"
  | "ST"
  | "SU"
  | "SV"
  | "SY"
  | "SZ"
  | "TC"
  | "TD"
  | "TF"
  | "TG"
  | "TH"
  | "TJ"
  | "TK"
  | "TL"
  | "TM"
  | "TN"
  | "TO"
  | "TP"
  | "TR"
  | "TT"
  | "TV"
  | "TW"
  | "TZ"
  | "UA"
  | "UG"
  | "UM"
  | "US"
  | "UY"
  | "UZ"
  | "VA"
  | "VC"
  | "VE"
  | "VG"
  | "VI"
  | "VN"
  | "VU"
  | "WF"
  | "WS"
  | "XC"
  | "XG"
  | "XI"
  | "XK"
  | "YE"
  | "YT"
  | "YU"
  | "ZA"
  | "ZM"
  | "ZR"
  | "ZW";

export const COUNTRIES: Record<CountryCode, Country> = {
  "AD": { "isoCode": "AD", "englishName": "Andorra", "nativeName": "Andorra" },
  "AE": {
    "isoCode": "AE",
    "englishName": "United Arab Emirates",
    "nativeName": "United Arab Emirates",
  },
  "AF": {
    "isoCode": "AF",
    "englishName": "Afghanistan",
    "nativeName": "Afghanistan",
  },
  "AG": {
    "isoCode": "AG",
    "englishName": "Antigua and Barbuda",
    "nativeName": "Antigua & Barbuda",
  },
  "AI": {
    "isoCode": "AI",
    "englishName": "Anguilla",
    "nativeName": "Anguilla",
  },
  "AL": { "isoCode": "AL", "englishName": "Albania", "nativeName": "Albania" },
  "AM": { "isoCode": "AM", "englishName": "Armenia", "nativeName": "Armenia" },
  "AN": {
    "isoCode": "AN",
    "englishName": "Netherlands Antilles",
    "nativeName": "Netherlands Antilles",
  },
  "AO": { "isoCode": "AO", "englishName": "Angola", "nativeName": "Angola" },
  "AQ": {
    "isoCode": "AQ",
    "englishName": "Antarctica",
    "nativeName": "Antarctica",
  },
  "AR": {
    "isoCode": "AR",
    "englishName": "Argentina",
    "nativeName": "Argentina",
  },
  "AS": {
    "isoCode": "AS",
    "englishName": "American Samoa",
    "nativeName": "American Samoa",
  },
  "AT": { "isoCode": "AT", "englishName": "Austria", "nativeName": "Austria" },
  "AU": {
    "isoCode": "AU",
    "englishName": "Australia",
    "nativeName": "Australia",
  },
  "AW": { "isoCode": "AW", "englishName": "Aruba", "nativeName": "Aruba" },
  "AZ": {
    "isoCode": "AZ",
    "englishName": "Azerbaijan",
    "nativeName": "Azerbaijan",
  },
  "BA": {
    "isoCode": "BA",
    "englishName": "Bosnia and Herzegovina",
    "nativeName": "Bosnia & Herzegovina",
  },
  "BB": {
    "isoCode": "BB",
    "englishName": "Barbados",
    "nativeName": "Barbados",
  },
  "BD": {
    "isoCode": "BD",
    "englishName": "Bangladesh",
    "nativeName": "Bangladesh",
  },
  "BE": { "isoCode": "BE", "englishName": "Belgium", "nativeName": "Belgium" },
  "BF": {
    "isoCode": "BF",
    "englishName": "Burkina Faso",
    "nativeName": "Burkina Faso",
  },
  "BG": {
    "isoCode": "BG",
    "englishName": "Bulgaria",
    "nativeName": "Bulgaria",
  },
  "BH": { "isoCode": "BH", "englishName": "Bahrain", "nativeName": "Bahrain" },
  "BI": { "isoCode": "BI", "englishName": "Burundi", "nativeName": "Burundi" },
  "BJ": { "isoCode": "BJ", "englishName": "Benin", "nativeName": "Benin" },
  "BM": { "isoCode": "BM", "englishName": "Bermuda", "nativeName": "Bermuda" },
  "BN": {
    "isoCode": "BN",
    "englishName": "Brunei Darussalam",
    "nativeName": "Brunei",
  },
  "BO": { "isoCode": "BO", "englishName": "Bolivia", "nativeName": "Bolivia" },
  "BR": { "isoCode": "BR", "englishName": "Brazil", "nativeName": "Brazil" },
  "BS": { "isoCode": "BS", "englishName": "Bahamas", "nativeName": "Bahamas" },
  "BT": { "isoCode": "BT", "englishName": "Bhutan", "nativeName": "Bhutan" },
  "BU": { "isoCode": "BU", "englishName": "Burma", "nativeName": "Burma" },
  "BV": {
    "isoCode": "BV",
    "englishName": "Bouvet Island",
    "nativeName": "Bouvet Island",
  },
  "BW": {
    "isoCode": "BW",
    "englishName": "Botswana",
    "nativeName": "Botswana",
  },
  "BY": { "isoCode": "BY", "englishName": "Belarus", "nativeName": "Belarus" },
  "BZ": { "isoCode": "BZ", "englishName": "Belize", "nativeName": "Belize" },
  "CA": { "isoCode": "CA", "englishName": "Canada", "nativeName": "Canada" },
  "CC": {
    "isoCode": "CC",
    "englishName": "Cocos  Islands",
    "nativeName": "Cocos (Keeling) Islands",
  },
  "CD": {
    "isoCode": "CD",
    "englishName": "Congo",
    "nativeName": "Democratic Republic of the Congo (Kinshasa)",
  },
  "CF": {
    "isoCode": "CF",
    "englishName": "Central African Republic",
    "nativeName": "Central African Republic",
  },
  "CG": {
    "isoCode": "CG",
    "englishName": "Congo",
    "nativeName": "Republic of the Congo (Brazzaville)",
  },
  "CH": {
    "isoCode": "CH",
    "englishName": "Switzerland",
    "nativeName": "Switzerland",
  },
  "CI": {
    "isoCode": "CI",
    "englishName": "Cote D'Ivoire",
    "nativeName": "Côte d’Ivoire",
  },
  "CK": {
    "isoCode": "CK",
    "englishName": "Cook Islands",
    "nativeName": "Cook Islands",
  },
  "CL": { "isoCode": "CL", "englishName": "Chile", "nativeName": "Chile" },
  "CM": {
    "isoCode": "CM",
    "englishName": "Cameroon",
    "nativeName": "Cameroon",
  },
  "CN": { "isoCode": "CN", "englishName": "China", "nativeName": "China" },
  "CO": {
    "isoCode": "CO",
    "englishName": "Colombia",
    "nativeName": "Colombia",
  },
  "CR": {
    "isoCode": "CR",
    "englishName": "Costa Rica",
    "nativeName": "Costa Rica",
  },
  "CS": {
    "isoCode": "CS",
    "englishName": "Serbia and Montenegro",
    "nativeName": "Serbia and Montenegro",
  },
  "CU": { "isoCode": "CU", "englishName": "Cuba", "nativeName": "Cuba" },
  "CV": {
    "isoCode": "CV",
    "englishName": "Cape Verde",
    "nativeName": "Cape Verde",
  },
  "CX": {
    "isoCode": "CX",
    "englishName": "Christmas Island",
    "nativeName": "Christmas Island",
  },
  "CY": { "isoCode": "CY", "englishName": "Cyprus", "nativeName": "Cyprus" },
  "CZ": {
    "isoCode": "CZ",
    "englishName": "Czech Republic",
    "nativeName": "Czech Republic",
  },
  "DE": { "isoCode": "DE", "englishName": "Germany", "nativeName": "Germany" },
  "DJ": {
    "isoCode": "DJ",
    "englishName": "Djibouti",
    "nativeName": "Djibouti",
  },
  "DK": { "isoCode": "DK", "englishName": "Denmark", "nativeName": "Denmark" },
  "DM": {
    "isoCode": "DM",
    "englishName": "Dominica",
    "nativeName": "Dominica",
  },
  "DO": {
    "isoCode": "DO",
    "englishName": "Dominican Republic",
    "nativeName": "Dominican Republic",
  },
  "DZ": { "isoCode": "DZ", "englishName": "Algeria", "nativeName": "Algeria" },
  "EC": { "isoCode": "EC", "englishName": "Ecuador", "nativeName": "Ecuador" },
  "EE": { "isoCode": "EE", "englishName": "Estonia", "nativeName": "Estonia" },
  "EG": { "isoCode": "EG", "englishName": "Egypt", "nativeName": "Egypt" },
  "EH": {
    "isoCode": "EH",
    "englishName": "Western Sahara",
    "nativeName": "Western Sahara",
  },
  "ER": { "isoCode": "ER", "englishName": "Eritrea", "nativeName": "Eritrea" },
  "ES": { "isoCode": "ES", "englishName": "Spain", "nativeName": "Spain" },
  "ET": {
    "isoCode": "ET",
    "englishName": "Ethiopia",
    "nativeName": "Ethiopia",
  },
  "FI": { "isoCode": "FI", "englishName": "Finland", "nativeName": "Finland" },
  "FJ": { "isoCode": "FJ", "englishName": "Fiji", "nativeName": "Fiji" },
  "FK": {
    "isoCode": "FK",
    "englishName": "Falkland Islands",
    "nativeName": "Falkland Islands",
  },
  "FM": {
    "isoCode": "FM",
    "englishName": "Micronesia",
    "nativeName": "Micronesia",
  },
  "FO": {
    "isoCode": "FO",
    "englishName": "Faeroe Islands",
    "nativeName": "Faroe Islands",
  },
  "FR": { "isoCode": "FR", "englishName": "France", "nativeName": "France" },
  "GA": { "isoCode": "GA", "englishName": "Gabon", "nativeName": "Gabon" },
  "GB": {
    "isoCode": "GB",
    "englishName": "United Kingdom",
    "nativeName": "United Kingdom",
  },
  "GD": { "isoCode": "GD", "englishName": "Grenada", "nativeName": "Grenada" },
  "GE": { "isoCode": "GE", "englishName": "Georgia", "nativeName": "Georgia" },
  "GF": {
    "isoCode": "GF",
    "englishName": "French Guiana",
    "nativeName": "French Guiana",
  },
  "GH": { "isoCode": "GH", "englishName": "Ghana", "nativeName": "Ghana" },
  "GI": {
    "isoCode": "GI",
    "englishName": "Gibraltar",
    "nativeName": "Gibraltar",
  },
  "GL": {
    "isoCode": "GL",
    "englishName": "Greenland",
    "nativeName": "Greenland",
  },
  "GM": { "isoCode": "GM", "englishName": "Gambia", "nativeName": "Gambia" },
  "GN": { "isoCode": "GN", "englishName": "Guinea", "nativeName": "Guinea" },
  "GP": {
    "isoCode": "GP",
    "englishName": "Guadaloupe",
    "nativeName": "Guadeloupe",
  },
  "GQ": {
    "isoCode": "GQ",
    "englishName": "Equatorial Guinea",
    "nativeName": "Equatorial Guinea",
  },
  "GR": { "isoCode": "GR", "englishName": "Greece", "nativeName": "Greece" },
  "GS": {
    "isoCode": "GS",
    "englishName": "South Georgia and the South Sandwich Islands",
    "nativeName": "South Georgia & South Sandwich Islands",
  },
  "GT": {
    "isoCode": "GT",
    "englishName": "Guatemala",
    "nativeName": "Guatemala",
  },
  "GU": { "isoCode": "GU", "englishName": "Guam", "nativeName": "Guam" },
  "GW": {
    "isoCode": "GW",
    "englishName": "Guinea-Bissau",
    "nativeName": "Guinea-Bissau",
  },
  "GY": { "isoCode": "GY", "englishName": "Guyana", "nativeName": "Guyana" },
  "HK": {
    "isoCode": "HK",
    "englishName": "Hong Kong",
    "nativeName": "Hong Kong SAR China",
  },
  "HM": {
    "isoCode": "HM",
    "englishName": "Heard and McDonald Islands",
    "nativeName": "Heard & McDonald Islands",
  },
  "HN": {
    "isoCode": "HN",
    "englishName": "Honduras",
    "nativeName": "Honduras",
  },
  "HR": { "isoCode": "HR", "englishName": "Croatia", "nativeName": "Croatia" },
  "HT": { "isoCode": "HT", "englishName": "Haiti", "nativeName": "Haiti" },
  "HU": { "isoCode": "HU", "englishName": "Hungary", "nativeName": "Hungary" },
  "ID": {
    "isoCode": "ID",
    "englishName": "Indonesia",
    "nativeName": "Indonesia",
  },
  "IE": { "isoCode": "IE", "englishName": "Ireland", "nativeName": "Ireland" },
  "IL": { "isoCode": "IL", "englishName": "Israel", "nativeName": "Israel" },
  "IN": { "isoCode": "IN", "englishName": "India", "nativeName": "India" },
  "IO": {
    "isoCode": "IO",
    "englishName": "British Indian Ocean Territory",
    "nativeName": "British Indian Ocean Territory",
  },
  "IQ": { "isoCode": "IQ", "englishName": "Iraq", "nativeName": "Iraq" },
  "IR": { "isoCode": "IR", "englishName": "Iran", "nativeName": "Iran" },
  "IS": { "isoCode": "IS", "englishName": "Iceland", "nativeName": "Iceland" },
  "IT": { "isoCode": "IT", "englishName": "Italy", "nativeName": "Italy" },
  "JM": { "isoCode": "JM", "englishName": "Jamaica", "nativeName": "Jamaica" },
  "JO": { "isoCode": "JO", "englishName": "Jordan", "nativeName": "Jordan" },
  "JP": { "isoCode": "JP", "englishName": "Japan", "nativeName": "Japan" },
  "KE": { "isoCode": "KE", "englishName": "Kenya", "nativeName": "Kenya" },
  "KG": {
    "isoCode": "KG",
    "englishName": "Kyrgyz Republic",
    "nativeName": "Kyrgyzstan",
  },
  "KH": {
    "isoCode": "KH",
    "englishName": "Cambodia",
    "nativeName": "Cambodia",
  },
  "KI": {
    "isoCode": "KI",
    "englishName": "Kiribati",
    "nativeName": "Kiribati",
  },
  "KM": { "isoCode": "KM", "englishName": "Comoros", "nativeName": "Comoros" },
  "KN": {
    "isoCode": "KN",
    "englishName": "St. Kitts and Nevis",
    "nativeName": "St. Kitts & Nevis",
  },
  "KP": {
    "isoCode": "KP",
    "englishName": "North Korea",
    "nativeName": "North Korea",
  },
  "KR": {
    "isoCode": "KR",
    "englishName": "South Korea",
    "nativeName": "South Korea",
  },
  "KW": { "isoCode": "KW", "englishName": "Kuwait", "nativeName": "Kuwait" },
  "KY": {
    "isoCode": "KY",
    "englishName": "Cayman Islands",
    "nativeName": "Cayman Islands",
  },
  "KZ": {
    "isoCode": "KZ",
    "englishName": "Kazakhstan",
    "nativeName": "Kazakhstan",
  },
  "LA": {
    "isoCode": "LA",
    "englishName": "Lao People's Democratic Republic",
    "nativeName": "Laos",
  },
  "LB": { "isoCode": "LB", "englishName": "Lebanon", "nativeName": "Lebanon" },
  "LC": {
    "isoCode": "LC",
    "englishName": "St. Lucia",
    "nativeName": "St. Lucia",
  },
  "LI": {
    "isoCode": "LI",
    "englishName": "Liechtenstein",
    "nativeName": "Liechtenstein",
  },
  "LK": {
    "isoCode": "LK",
    "englishName": "Sri Lanka",
    "nativeName": "Sri Lanka",
  },
  "LR": { "isoCode": "LR", "englishName": "Liberia", "nativeName": "Liberia" },
  "LS": { "isoCode": "LS", "englishName": "Lesotho", "nativeName": "Lesotho" },
  "LT": {
    "isoCode": "LT",
    "englishName": "Lithuania",
    "nativeName": "Lithuania",
  },
  "LU": {
    "isoCode": "LU",
    "englishName": "Luxembourg",
    "nativeName": "Luxembourg",
  },
  "LV": { "isoCode": "LV", "englishName": "Latvia", "nativeName": "Latvia" },
  "LY": {
    "isoCode": "LY",
    "englishName": "Libyan Arab Jamahiriya",
    "nativeName": "Libya",
  },
  "MA": { "isoCode": "MA", "englishName": "Morocco", "nativeName": "Morocco" },
  "MC": { "isoCode": "MC", "englishName": "Monaco", "nativeName": "Monaco" },
  "MD": { "isoCode": "MD", "englishName": "Moldova", "nativeName": "Moldova" },
  "ME": {
    "isoCode": "ME",
    "englishName": "Montenegro",
    "nativeName": "Montenegro",
  },
  "MG": {
    "isoCode": "MG",
    "englishName": "Madagascar",
    "nativeName": "Madagascar",
  },
  "MH": {
    "isoCode": "MH",
    "englishName": "Marshall Islands",
    "nativeName": "Marshall Islands",
  },
  "MK": {
    "isoCode": "MK",
    "englishName": "Macedonia",
    "nativeName": "Macedonia",
  },
  "ML": { "isoCode": "ML", "englishName": "Mali", "nativeName": "Mali" },
  "MM": {
    "isoCode": "MM",
    "englishName": "Myanmar",
    "nativeName": "Myanmar (Burma)",
  },
  "MN": {
    "isoCode": "MN",
    "englishName": "Mongolia",
    "nativeName": "Mongolia",
  },
  "MO": {
    "isoCode": "MO",
    "englishName": "Macao",
    "nativeName": "Macau SAR China",
  },
  "MP": {
    "isoCode": "MP",
    "englishName": "Northern Mariana Islands",
    "nativeName": "Northern Mariana Islands",
  },
  "MQ": {
    "isoCode": "MQ",
    "englishName": "Martinique",
    "nativeName": "Martinique",
  },
  "MR": {
    "isoCode": "MR",
    "englishName": "Mauritania",
    "nativeName": "Mauritania",
  },
  "MS": {
    "isoCode": "MS",
    "englishName": "Montserrat",
    "nativeName": "Montserrat",
  },
  "MT": { "isoCode": "MT", "englishName": "Malta", "nativeName": "Malta" },
  "MU": {
    "isoCode": "MU",
    "englishName": "Mauritius",
    "nativeName": "Mauritius",
  },
  "MV": {
    "isoCode": "MV",
    "englishName": "Maldives",
    "nativeName": "Maldives",
  },
  "MW": { "isoCode": "MW", "englishName": "Malawi", "nativeName": "Malawi" },
  "MX": { "isoCode": "MX", "englishName": "Mexico", "nativeName": "Mexico" },
  "MY": {
    "isoCode": "MY",
    "englishName": "Malaysia",
    "nativeName": "Malaysia",
  },
  "MZ": {
    "isoCode": "MZ",
    "englishName": "Mozambique",
    "nativeName": "Mozambique",
  },
  "NA": { "isoCode": "NA", "englishName": "Namibia", "nativeName": "Namibia" },
  "NC": {
    "isoCode": "NC",
    "englishName": "New Caledonia",
    "nativeName": "New Caledonia",
  },
  "NE": { "isoCode": "NE", "englishName": "Niger", "nativeName": "Niger" },
  "NF": {
    "isoCode": "NF",
    "englishName": "Norfolk Island",
    "nativeName": "Norfolk Island",
  },
  "NG": { "isoCode": "NG", "englishName": "Nigeria", "nativeName": "Nigeria" },
  "NI": {
    "isoCode": "NI",
    "englishName": "Nicaragua",
    "nativeName": "Nicaragua",
  },
  "NL": {
    "isoCode": "NL",
    "englishName": "Netherlands",
    "nativeName": "Netherlands",
  },
  "NO": { "isoCode": "NO", "englishName": "Norway", "nativeName": "Norway" },
  "NP": { "isoCode": "NP", "englishName": "Nepal", "nativeName": "Nepal" },
  "NR": { "isoCode": "NR", "englishName": "Nauru", "nativeName": "Nauru" },
  "NU": { "isoCode": "NU", "englishName": "Niue", "nativeName": "Niue" },
  "NZ": {
    "isoCode": "NZ",
    "englishName": "New Zealand",
    "nativeName": "New Zealand",
  },
  "OM": { "isoCode": "OM", "englishName": "Oman", "nativeName": "Oman" },
  "PA": { "isoCode": "PA", "englishName": "Panama", "nativeName": "Panama" },
  "PE": { "isoCode": "PE", "englishName": "Peru", "nativeName": "Peru" },
  "PF": {
    "isoCode": "PF",
    "englishName": "French Polynesia",
    "nativeName": "French Polynesia",
  },
  "PG": {
    "isoCode": "PG",
    "englishName": "Papua New Guinea",
    "nativeName": "Papua New Guinea",
  },
  "PH": {
    "isoCode": "PH",
    "englishName": "Philippines",
    "nativeName": "Philippines",
  },
  "PK": {
    "isoCode": "PK",
    "englishName": "Pakistan",
    "nativeName": "Pakistan",
  },
  "PL": { "isoCode": "PL", "englishName": "Poland", "nativeName": "Poland" },
  "PM": {
    "isoCode": "PM",
    "englishName": "St. Pierre and Miquelon",
    "nativeName": "St. Pierre & Miquelon",
  },
  "PN": {
    "isoCode": "PN",
    "englishName": "Pitcairn Island",
    "nativeName": "Pitcairn Islands",
  },
  "PR": {
    "isoCode": "PR",
    "englishName": "Puerto Rico",
    "nativeName": "Puerto Rico",
  },
  "PS": {
    "isoCode": "PS",
    "englishName": "Palestinian Territory",
    "nativeName": "Palestinian Territories",
  },
  "PT": {
    "isoCode": "PT",
    "englishName": "Portugal",
    "nativeName": "Portugal",
  },
  "PW": { "isoCode": "PW", "englishName": "Palau", "nativeName": "Palau" },
  "PY": {
    "isoCode": "PY",
    "englishName": "Paraguay",
    "nativeName": "Paraguay",
  },
  "QA": { "isoCode": "QA", "englishName": "Qatar", "nativeName": "Qatar" },
  "RE": { "isoCode": "RE", "englishName": "Reunion", "nativeName": "Réunion" },
  "RO": { "isoCode": "RO", "englishName": "Romania", "nativeName": "Romania" },
  "RS": { "isoCode": "RS", "englishName": "Serbia", "nativeName": "Serbia" },
  "RU": { "isoCode": "RU", "englishName": "Russia", "nativeName": "Russia" },
  "RW": { "isoCode": "RW", "englishName": "Rwanda", "nativeName": "Rwanda" },
  "SA": {
    "isoCode": "SA",
    "englishName": "Saudi Arabia",
    "nativeName": "Saudi Arabia",
  },
  "SB": {
    "isoCode": "SB",
    "englishName": "Solomon Islands",
    "nativeName": "Solomon Islands",
  },
  "SC": {
    "isoCode": "SC",
    "englishName": "Seychelles",
    "nativeName": "Seychelles",
  },
  "SD": { "isoCode": "SD", "englishName": "Sudan", "nativeName": "Sudan" },
  "SE": { "isoCode": "SE", "englishName": "Sweden", "nativeName": "Sweden" },
  "SG": {
    "isoCode": "SG",
    "englishName": "Singapore",
    "nativeName": "Singapore",
  },
  "SH": {
    "isoCode": "SH",
    "englishName": "St. Helena",
    "nativeName": "St. Helena",
  },
  "SI": {
    "isoCode": "SI",
    "englishName": "Slovenia",
    "nativeName": "Slovenia",
  },
  "SJ": {
    "isoCode": "SJ",
    "englishName": "Svalbard & Jan Mayen Islands",
    "nativeName": "Svalbard & Jan Mayen",
  },
  "SK": {
    "isoCode": "SK",
    "englishName": "Slovakia",
    "nativeName": "Slovakia",
  },
  "SL": {
    "isoCode": "SL",
    "englishName": "Sierra Leone",
    "nativeName": "Sierra Leone",
  },
  "SM": {
    "isoCode": "SM",
    "englishName": "San Marino",
    "nativeName": "San Marino",
  },
  "SN": { "isoCode": "SN", "englishName": "Senegal", "nativeName": "Senegal" },
  "SO": { "isoCode": "SO", "englishName": "Somalia", "nativeName": "Somalia" },
  "SR": {
    "isoCode": "SR",
    "englishName": "Suriname",
    "nativeName": "Suriname",
  },
  "SS": {
    "isoCode": "SS",
    "englishName": "South Sudan",
    "nativeName": "South Sudan",
  },
  "ST": {
    "isoCode": "ST",
    "englishName": "Sao Tome and Principe",
    "nativeName": "São Tomé & Príncipe",
  },
  "SU": {
    "isoCode": "SU",
    "englishName": "Soviet Union",
    "nativeName": "Soviet Union",
  },
  "SV": {
    "isoCode": "SV",
    "englishName": "El Salvador",
    "nativeName": "El Salvador",
  },
  "SY": {
    "isoCode": "SY",
    "englishName": "Syrian Arab Republic",
    "nativeName": "Syria",
  },
  "SZ": {
    "isoCode": "SZ",
    "englishName": "Swaziland",
    "nativeName": "Eswatini (Swaziland)",
  },
  "TC": {
    "isoCode": "TC",
    "englishName": "Turks and Caicos Islands",
    "nativeName": "Turks & Caicos Islands",
  },
  "TD": { "isoCode": "TD", "englishName": "Chad", "nativeName": "Chad" },
  "TF": {
    "isoCode": "TF",
    "englishName": "French Southern Territories",
    "nativeName": "French Southern Territories",
  },
  "TG": { "isoCode": "TG", "englishName": "Togo", "nativeName": "Togo" },
  "TH": {
    "isoCode": "TH",
    "englishName": "Thailand",
    "nativeName": "Thailand",
  },
  "TJ": {
    "isoCode": "TJ",
    "englishName": "Tajikistan",
    "nativeName": "Tajikistan",
  },
  "TK": { "isoCode": "TK", "englishName": "Tokelau", "nativeName": "Tokelau" },
  "TL": {
    "isoCode": "TL",
    "englishName": "Timor-Leste",
    "nativeName": "Timor-Leste",
  },
  "TM": {
    "isoCode": "TM",
    "englishName": "Turkmenistan",
    "nativeName": "Turkmenistan",
  },
  "TN": { "isoCode": "TN", "englishName": "Tunisia", "nativeName": "Tunisia" },
  "TO": { "isoCode": "TO", "englishName": "Tonga", "nativeName": "Tonga" },
  "TP": {
    "isoCode": "TP",
    "englishName": "East Timor",
    "nativeName": "East Timor",
  },
  "TR": { "isoCode": "TR", "englishName": "Turkey", "nativeName": "Turkey" },
  "TT": {
    "isoCode": "TT",
    "englishName": "Trinidad and Tobago",
    "nativeName": "Trinidad & Tobago",
  },
  "TV": { "isoCode": "TV", "englishName": "Tuvalu", "nativeName": "Tuvalu" },
  "TW": { "isoCode": "TW", "englishName": "Taiwan", "nativeName": "Taiwan" },
  "TZ": {
    "isoCode": "TZ",
    "englishName": "Tanzania",
    "nativeName": "Tanzania",
  },
  "UA": { "isoCode": "UA", "englishName": "Ukraine", "nativeName": "Ukraine" },
  "UG": { "isoCode": "UG", "englishName": "Uganda", "nativeName": "Uganda" },
  "UM": {
    "isoCode": "UM",
    "englishName": "United States Minor Outlying Islands",
    "nativeName": "U.S. Outlying Islands",
  },
  "US": {
    "isoCode": "US",
    "englishName": "United States of America",
    "nativeName": "United States",
  },
  "UY": { "isoCode": "UY", "englishName": "Uruguay", "nativeName": "Uruguay" },
  "UZ": {
    "isoCode": "UZ",
    "englishName": "Uzbekistan",
    "nativeName": "Uzbekistan",
  },
  "VA": {
    "isoCode": "VA",
    "englishName": "Holy See",
    "nativeName": "Vatican City",
  },
  "VC": {
    "isoCode": "VC",
    "englishName": "St. Vincent and the Grenadines",
    "nativeName": "St. Vincent & Grenadines",
  },
  "VE": {
    "isoCode": "VE",
    "englishName": "Venezuela",
    "nativeName": "Venezuela",
  },
  "VG": {
    "isoCode": "VG",
    "englishName": "British Virgin Islands",
    "nativeName": "British Virgin Islands",
  },
  "VI": {
    "isoCode": "VI",
    "englishName": "US Virgin Islands",
    "nativeName": "U.S. Virgin Islands",
  },
  "VN": { "isoCode": "VN", "englishName": "Vietnam", "nativeName": "Vietnam" },
  "VU": { "isoCode": "VU", "englishName": "Vanuatu", "nativeName": "Vanuatu" },
  "WF": {
    "isoCode": "WF",
    "englishName": "Wallis and Futuna Islands",
    "nativeName": "Wallis & Futuna",
  },
  "WS": { "isoCode": "WS", "englishName": "Samoa", "nativeName": "Samoa" },
  "XC": {
    "isoCode": "XC",
    "englishName": "Czechoslovakia",
    "nativeName": "Czechoslovakia",
  },
  "XG": {
    "isoCode": "XG",
    "englishName": "East Germany",
    "nativeName": "East Germany",
  },
  "XI": {
    "isoCode": "XI",
    "englishName": "Northern Ireland",
    "nativeName": "Northern Ireland",
  },
  "XK": { "isoCode": "XK", "englishName": "Kosovo", "nativeName": "Kosovo" },
  "YE": { "isoCode": "YE", "englishName": "Yemen", "nativeName": "Yemen" },
  "YT": { "isoCode": "YT", "englishName": "Mayotte", "nativeName": "Mayotte" },
  "YU": {
    "isoCode": "YU",
    "englishName": "Yugoslavia",
    "nativeName": "Yugoslavia",
  },
  "ZA": {
    "isoCode": "ZA",
    "englishName": "South Africa",
    "nativeName": "South Africa",
  },
  "ZM": { "isoCode": "ZM", "englishName": "Zambia", "nativeName": "Zambia" },
  "ZR": { "isoCode": "ZR", "englishName": "Zaire", "nativeName": "Zaire" },
  "ZW": {
    "isoCode": "ZW",
    "englishName": "Zimbabwe",
    "nativeName": "Zimbabwe",
  },
};
