/**
 * @internal
 * Script to run locally in development to fetch languages and cache the
 * response.
 */
import { resolve } from "https://deno.land/std@0.170.0/path/mod.ts";
import { TMDB_API_KEY } from "../../env.ts";
import { getCountries } from "./getCountries.ts";

const __dirname = new URL(".", import.meta.url).pathname;
const CACHE_FILE_PATH = resolve(__dirname, "countries.ts");
const countries = await getCountries(TMDB_API_KEY);
const countriesTS = `// This file is generated by ./updateCacheFile.ts
import { Country } from "./types.ts"

export type CountryCode = ${
  Object.keys(countries)
    .map((countryCode) => `"${countryCode}"`)
    .join(" | ")
}

export const COUNTRIES: Record<CountryCode, Country> = ${
  JSON.stringify(countries)
}
`;

await Deno.writeTextFile(CACHE_FILE_PATH, countriesTS);
await Deno.run({ cmd: ["deno", "fmt", CACHE_FILE_PATH] }).status();
