// This file is generated by ./updateCacheFile.ts
export type MovieGenre =
  | "Adventure"
  | "Fantasy"
  | "Animation"
  | "Drama"
  | "Horror"
  | "Action"
  | "Comedy"
  | "History"
  | "Western"
  | "Thriller"
  | "Crime"
  | "Documentary"
  | "Science Fiction"
  | "Mystery"
  | "Music"
  | "Romance"
  | "Family"
  | "War"
  | "TV Movie";

export const MOVIE_GENRES: Record<number, MovieGenre> = {
  "12": "Adventure",
  "14": "Fantasy",
  "16": "Animation",
  "18": "Drama",
  "27": "Horror",
  "28": "Action",
  "35": "Comedy",
  "36": "History",
  "37": "Western",
  "53": "Thriller",
  "80": "Crime",
  "99": "Documentary",
  "878": "Science Fiction",
  "9648": "Mystery",
  "10402": "Music",
  "10749": "Romance",
  "10751": "Family",
  "10752": "War",
  "10770": "TV Movie",
};
