/**
 * @internal
 * Script to run locally in development to fetch genres and cache the response.
 */
import { resolve } from "https://deno.land/std@0.170.0/path/mod.ts";
import { TMDB_API_KEY } from "../../env.ts";
import { tsStringUnion } from "../../utils/codeGen.ts";
import { getMovieGenres } from "./getMovieGenres.ts";

const __dirname = new URL(".", import.meta.url).pathname;
const CACHE_FILE_PATH = resolve(__dirname, "genres.ts");
const movieGenreMap = await getMovieGenres(TMDB_API_KEY);
const genreTS = `// This file is generated by ./updateCacheFile.ts
export type MovieGenre = ${tsStringUnion(Object.values(movieGenreMap))}

export const MOVIE_GENRES: Record<number, MovieGenre> = ${
  JSON.stringify(movieGenreMap)
}
`;

await Deno.writeTextFile(CACHE_FILE_PATH, genreTS);
await Deno.run({ cmd: ["deno", "fmt", CACHE_FILE_PATH] }).status();
